### ISSUE TITLE
`index.html` is replaced with template contents on build

### ISSUE THREAD

**Issue by timhaywood** [hyperbrew/vite-cep-plugin#12]
I had some additional script tags in `index.html` for doing things like loading Google Analytics, fonts etc. During dev, vite uses your `index.html` file in `/src` so all works well.

On build, `vite-cep-plugin` replaces the html file with the [template contents](src/templates/html-template.ts), removing any changes you've done to `index.html` yourself.

I should be able to get around this by moving things into the `ts` files — but I wonder if it might be possible to either:

- **Add the needed script/css files to `index.html` without replacing it's contents**

  Looks like it should be possible to return an array of tags to be added to the existing html, rather than the entire html string?
  > An array of tag descriptor objects ({ tag, attrs, children }) to inject to the existing HTML. Each tag can also specify where it should be injected to (default is prepending to `<head>`)
  > — [`transformIndexHtml` docs](https://vitejs.dev/guide/api-plugin.html#transformindexhtml)

- **Callout that your `index.html` is replaced in the `bolt-cep` README**

Happy to take a look at modifying the `transformIndexHtml` implementation to see if I can get this working. Thanks!

**Comment by timhaywood** [comment]
Haven't tested it yet 😅 but something like this might work:

```ts
// transformIndexHtml() { ...
const tags: HtmlTagDescriptor[] = [
  { tag: "script", children: injectRequire },
  { tag: "script", attrs: { src: `..${jsFileName}` } },
];

if (cssFileNames) {
  tags.push(
    ...cssFileNames.map((file) => ({
      tag: "link",
      attrs: { rel: "stylesheet", href: `..${file}` },
    }))
  );
}

if (debugReact) {
  tags.push({
    tag: "script",
    attrs: { src: "http://localhost:8097" },
    injectTo: "body",
  });
}

return tags;
```

**Comment by timhaywood** [comment]
This implementation seemed to work for my repo, so created a pull request 👍 
(But needs a bit more testing I think).

The default `index.html` in bolt-cep would also need updating, to add a few things that are missing from the template (e.g. DOCTYPE, lang attribute etc).

**Comment by justintaylor-dev** [comment]
Thanks for the help, should be good to go now 👍

**Comment by timhaywood** [comment]
So fast! Thanks Justin 🙏
