### ISSUE TITLE
Permission denied ./ZXPSignCmd

### ISSUE THREAD

**Issue by tb-b** [hyperbrew/vite-cep-plugin#5]
I'm getting Permission denied on Mac (M1 if relevant) with ./ZXPSignCmd, coming from here

`var zxpCmd = os.platform() == "win32" ? "ZXPSignCmd" : "./ZXPSignCmd";`

Running it without "./" seems to solve the permission issue for me.

**Comment by justintaylor-dev** [comment]
Strange. Did you try a fresh clone of Bolt CEP or this plugin? I recently updated the git permissions for that binary in this project for Mac, and they might not get updated without a fresh copy.

**Comment by tb-b** [comment]
Reinstall of vite-cep-plugin in Bolt seem to have helped. Though this copy of Bolt was installed earlier today so I'm not sure why the vite-cep-plugin reinstall helped since it's the same version.

**Comment by justintaylor-dev** [comment]
Cool, I think file permissions with Git are a bit funky, and require a fresh copy. Gonna close this one out for now, but open a new Issue if it crops up again. Thanks!

**Comment by tb-b** [comment]
Seems to be back again. Reinstall has no effect, but it seems to be random (was running fine for a few days) so I'm suspecting problem on my end rather than the package.

- latest vite-cep-plugin
- yarn zxp -> build successful -> zpx sign step -> /bin/sh: ./ZXPSignCmd: Permission denied

the only solution I've found so far is to remove ./ as mentioned above

**Comment by justintaylor-dev** [comment]
@iconictb removing `./` errors out for me on Mac. It sounds like you have `ZXPSignCmd` installed globally, can you test if it works in any directory?

Maybe try a fresh install in a directory you reset the permissions on.

**Comment by tb-b** [comment]
> 

Yes, I had it globally installed but removing wouldn't get rid of the permissions error. Had to run `chmod 700 ./ZXPSignCmd` in vite-cep-plugin/lib/bin - seems to be working fine, if it pops up again I'll just edit the permissions instead of removing ./ from the path. Can close, thanks!

**Comment by justintaylor-dev** [comment]
Thanks for the tip, will note in the docs.

**Comment by alexIV-0** [comment]
Hello. I am a newbie and I tried just to build a Demo project (which is created by default) with nfkp zxp b got the same error

/bin/sh: ./ZXPSignCmd: Permission denied

I read the thread and do not understand anything, can you tell me what to do step by step.

**Comment by justintaylor-dev** [comment]
@alexIV-0  Run

`cd node_modules/vite-cep-plugin/lib/bin`
`chmod 700 ./ZXPSignCmd`
