### ISSUE TITLE
Symlink 'global' fails silently on Mac

### ISSUE THREAD

**Issue by tb-b** [hyperbrew/vite-cep-plugin#7]
This only affects `symlink: 'global'` - possibly only on Mac

`Library/Application Support/Adobe/CEP/extensions` needs admin password on Mac by default, so running `yarn build` silently fails during symlink creation (shows "symlink already exists → succeeded").

`sudo yarn build` works, but then it creates dist/cep and zxp folders with root owner, therefore rimraf throws error if run next time without sudo

Quick workaround is to create that symlink manually via ln -s and all subsequent runs will pick it up as already existing

**Comment by justintaylor-dev** [comment]
Thanks for finding this, fixed in the latest 0.1.9. 

Since Mac does require admin permissions with global, after running `yarn build`, run `sudo yarn symlink` to create the global symlink.
